services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres_ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_ecommerce:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: medusa_redis_ecommerce
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data_ecommerce:
